### ISSUE TITLE
Crash on sending image to device

### ISSUE THREAD

**Issue by milosmns** [gdg-berlin-android/ZeBadge#24]
```console
2023-05-11 18:22:21.918 28288-28288 Compatibil...geReporter de.berlindroid.zeapp                 D  Compat change id reported: 147798919; UID 10247; state: ENABLED
2023-05-11 18:22:28.356 28288-28298 rlindroid.zeapp         de.berlindroid.zeapp                 I  Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
2023-05-11 18:22:33.198 28288-28288 OnBackInvokedCallback   de.berlindroid.zeapp                 W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2023-05-11 18:22:33.235 28288-28288 rlindroid.zeapp         de.berlindroid.zeapp                 W  Method boolean androidx.compose.runtime.snapshots.SnapshotStateList.conditionalUpdate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
                                                                                                    Common causes for lock verification issues are non-optimized dex code
                                                                                                    and incorrect proguard optimizations.
2023-05-11 18:22:33.235 28288-28288 rlindroid.zeapp         de.berlindroid.zeapp                 W  Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2023-05-11 18:22:33.235 28288-28288 rlindroid.zeapp         de.berlindroid.zeapp                 W  Method void androidx.compose.runtime.snapshots.SnapshotStateList.update(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2023-05-11 18:22:36.511 28288-28309 OpenGLRenderer          de.berlindroid.zeapp                 D  endAllActiveAnimators on 0xb4000072a107baf0 (UnprojectedRipple) with handle 0xb4000071b1071ad0
2023-05-11 18:22:37.330 28288-28299 rlindroid.zeapp         de.berlindroid.zeapp                 I  Background concurrent copying GC freed 277864(8565KB) AllocSpace objects, 6(656KB) LOS objects, 84% free, 4652KB/28MB, paused 119us,18us total 144.182ms
2023-05-11 18:22:37.336 28288-28301 System                  de.berlindroid.zeapp                 W  A resource failed to call close. 
2023-05-11 18:22:37.807 28288-28288 Compatibil...geReporter de.berlindroid.zeapp                 D  Compat change id reported: 160794467; UID 10247; state: ENABLED
--------- beginning of crash
2023-05-11 18:22:37.820 28288-28288 AndroidRuntime          de.berlindroid.zeapp                 E  FATAL EXCEPTION: main
                                                                                                    Process: de.berlindroid.zeapp, PID: 28288
                                                                                                    java.lang.IllegalArgumentException: de.berlindroid.zeapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
                                                                                                    	at de.berlindroid.zeapp.hardware.Badge.askPermissionAndRetry(Badge.kt:126)
                                                                                                    	at de.berlindroid.zeapp.hardware.Badge.sendToUsb(Badge.kt:66)
                                                                                                    	at de.berlindroid.zeapp.hardware.Badge.sendPage(Badge.kt:49)
                                                                                                    	at de.berlindroid.zeapp.vm.BadgeViewModel.sendPageToDevice(BadgeViewModel.kt:31)
                                                                                                    	at de.berlindroid.zeapp.MainActivityKt$ZePages$1$1$2$1$3.invoke(MainActivity.kt:135)
                                                                                                    	at de.berlindroid.zeapp.MainActivityKt$ZePages$1$1$2$1$3.invoke(MainActivity.kt:131)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:234)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:394)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
2023-05-11 18:22:37.821 28288-28288 AndroidRuntime          de.berlindroid.zeapp                 E  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4298)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15269)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6757)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6557)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6013)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6201)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6258)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9103)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9054)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9023)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9226)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b29dcdc, androidx.compose.runtime.BroadcastFrameClock@4641e5, StandaloneCoroutine{Cancelling}@21c04ba, AndroidUiDispatcher@13adf6b]
2023-05-11 18:22:37.843 28288-28288 Process                 de.berlindroid.zeapp                 I  Sending signal. PID: 28288 SIG: 9
---------------------------- PROCESS ENDED (28288) for package de.berlindroid.zeapp ----------------------------
```

**Comment by mariobodemann** [comment]
Wow, gotta say this FLAG_IMMUTABLE looks interesting. It needs to be added it to the USB permission request, or we don't target 31 ... ;-)

**Comment by milosmns** [comment]
I believe we agreed to target 35?!
